using AgricolaDH_GApp.DataAccess;
using AgricolaDH_GApp.Models;
using AgricolaDH_GApp.Services.Admin;
using AgricolaDH_GApp.ViewModels;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Diagnostics;
using System.IO;
using System.Text.RegularExpressions;
using System.Web;
using System.Xml;
using System.Xml.Serialization;

namespace AgricolaDH_GApp.Controllers
{
    public class SubirFacturaController : Controller
	{
		private readonly ILogger<RequisicionController> _logger;
		
		private readonly AppDbContext context;
        private ViewRenderService renderService;
		private OrdenDeCompraService ordenDeCompraService;

        public SubirFacturaController(ILogger<RequisicionController> logger, AppDbContext _ctx, ViewRenderService _renderService, OrdenDeCompraService _ordenDeCompraService)
		{
			_logger = logger;
			context = _ctx;
            ordenDeCompraService = _ordenDeCompraService;
			renderService = _renderService;
		}

		[HttpGet]
		public IActionResult Index()
		{
			SubirFacturaVM model = new SubirFacturaVM();
			model.subirFacturaList = ordenDeCompraService.SelectOrdenDeCompraTableList(OrdenDeCompraStatusEnumerators.Aceptado);

			return PartialView("~/Views/SubirFactura/Index.cshtml", model);
		}

        [HttpPost]
        public IActionResult SubirFactura(int IdOrdenDeCompra)
        {
            SubirFacturaVM model = new SubirFacturaVM();

			model.ordenDeCompra = ordenDeCompraService.SelectOrdenDeCompra(IdOrdenDeCompra);
            model.productosOrdenar = ordenDeCompraService.SelectProductosOrdenarSelected(IdOrdenDeCompra);

            return PartialView("~/Views/SubirFactura/SubirFacturaForm.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> SubirFacturaUpdate(SubirFacturaVM model)
        {

            int res = 0;
            bool allZero = true;
            foreach (var productoOrdenar in model.productosOrdenar)
            {
                if(productoOrdenar.Cantidad != 0)
                {
                    allZero = false;
                }
                res = ordenDeCompraService.UpdateProductoOrdenarConFactura(productoOrdenar);
            }

            if (res == 0)
            {
                if (allZero)
                {
                    res = ordenDeCompraService.UpdateOrdenDeCompraStatus(model.ordenDeCompra.IdOrdenDeCompra, OrdenDeCompraStatusEnumerators.Cancelado);
                }
                else
                {
                    res = ordenDeCompraService.UpdateOrdenDeCompraStatus(model.ordenDeCompra.IdOrdenDeCompra, OrdenDeCompraStatusEnumerators.PorIngresar);
                }

            }
            else
            {
                res = -1;
            }

            model = new SubirFacturaVM();
            model.subirFacturaList = ordenDeCompraService.SelectOrdenDeCompraTableList(OrdenDeCompraStatusEnumerators.Aceptado);

            return Json(new { res, url = await renderService.RenderViewToStringAsync("~/Views/SubirFactura/Index.cshtml", model) });

        }

        [HttpPost]
        public async Task<ActionResult> UploadFileAsync(int IdOrdenDeCompra, IFormFile file)
        {

            int res = 0;

            SubirFacturaVM model = new SubirFacturaVM();
            model.productosOrdenar = ordenDeCompraService.SelectProductosOrdenarSelected(IdOrdenDeCompra);

            try
            {
                var filePath = Path.GetTempFileName();

                using (var stream = System.IO.File.Create(filePath))
                {
                    // The formFile is the method parameter which type is IFormFile
                    // Saves the files to the local file system using a file name generated by the app.
                    await file.CopyToAsync(stream);
                }

                XmlDocument doc = new XmlDocument();
                doc.Load(filePath);

                List<string> productosOrdenarName = model.productosOrdenar.Select(m => m.Producto.ToLower()).ToList();

                foreach (XmlElement item in doc.GetElementsByTagName("cfdi:Concepto"))
                {
                    string descripcion = item.GetAttribute("Descripcion").ToLower();

                    var trasladoAttributes = item.FirstChild.FirstChild.FirstChild.Attributes[2];

                    RegexOptions options = RegexOptions.None;
                    Regex regex = new Regex("[ ]{2,}", options);
                    descripcion = regex.Replace(descripcion, " ");

                    if (descripcion != null && productosOrdenarName.Contains(descripcion)) 
                    {
                        int index = productosOrdenarName.FindIndex(m => m.Contains(descripcion));
                        model.productosOrdenar[index].Cantidad = Convert.ToInt32(Convert.ToDouble(item.GetAttribute("Cantidad")));
                        model.productosOrdenar[index].Total = Convert.ToDecimal(item.GetAttribute("Importe"));
                        model.productosOrdenar[index].Unidad = model.productosOrdenar[index].Total / model.productosOrdenar[index].Cantidad;
                    }
                }

                foreach(var productoOrdenar in model.productosOrdenar)
                {
                    if(productoOrdenar.Total == null || productoOrdenar.Total == 0)
                    {
                        productoOrdenar.Cantidad = 0;
                    }
                }

            }
            catch(Exception ex)
            {
                res = -1;
            }


            return Json(new { res, url = await renderService.RenderViewToStringAsync("~/Views/SubirFactura/ProductosOrdenar.cshtml", model) });

        }

        public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}